'use strict';

/* Controllers */

var canucksApp = angular.module('canucksApp', []);

canucksApp.controller('PlayersController', function($scope) {
  $scope.players = [
    {'name': 'POLAROID™ SLR 680',
     'brand': 'POLAROID™ 600-TYPE CAMERAS',
     'img': './img/cameras/POLAROID™ SLR 680 CAMERA.jpg',
     'age': 22},
    {'name': 'SUN 660 AF 600',
     'brand': 'POLAROID™ 600-TYPE CAMERAS',
     'img': './img/cameras/SUN 660 AF 600 CAMERA.jpg',
     'age': 22},
    {'name': 'POLAROID™ 600 – SQUAR',
     'brand': 'POLAROID™ 600-TYPE CAMERAS',
     'img': './img/cameras/POLAROID™ 600 CAMERA – SQUARE.jpg',
     'age': 22},
    {'name': 'POLAROID™ 600 - ROUND',
     'brand': 'POLAROID™ 600-TYPE CAMERAS',
     'img': './img/cameras/POLAROID™ 600 CAMERA – ROUND.jpg',
     'age': 22},
    {'name': 'ORIGINAL SX-70',
     'brand': 'POLAROID™ SX-70 CAMERAS',
     'img': './img/cameras/ORIGINAL SX-70 CAMERA.jpg',
     'age': 22},
    {'name': 'SX-70 MODEL 2 ALPHA 1',
     'brand': 'POLAROID™ SX-70 CAMERAS',
     'img': './img/cameras/SX-70 MODEL 2 ALPHA 1 CAMERA.jpg',
     'age': 22},
    {'name': 'POLAROID™ SX-70 MODEL 2',
     'brand': 'POLAROID™ SX-70 CAMERAS',
     'img': './img/cameras/POLAROID™ SX-70 MODEL 2 CAMERA.jpg',
     'age': 22},
    {'name': 'SX-70 SONAR',
     'brand': 'POLAROID™ SX-70 CAMERAS',
     'img': './img/cameras/SX-70 SONAR CAMERA.jpg',
     'age': 22},
    {'name': 'B-GRADE SPECTRA CAMERA',
     'brand': 'POLAROID™ IMAGE/SPECTRA CAMERAS',
     'img': './img/cameras/B-GRADE SPECTRA CAMERA.jpg',
     'age': 22},
    {'name': 'ONYX SPECTRA CAMERA',
     'brand': 'POLAROID™ IMAGE/SPECTRA CAMERAS',
     'img': './img/cameras/ONYX SPECTRA CAMERA.jpg',
     'age': 22},
    {'name': 'EOS 5D Mark III',
     'brand': 'Canon',
     'img': './img/cameras/EOS 5D Mark III.jpg',
     'age': 22},
    {'name': 'EOS Rebel SL1',
     'brand': 'Canon',
     'img': './img/cameras/EOS Rebel SL1 Body.jpg',
     'age': 22},
    {'name': 'EOS Rebel T5i',
     'brand': 'Canon',
     'img': './img/cameras/EOS Rebel T5i Body.jpg',
     'age': 22},
    {'name': 'EOS 7D Mark II',
     'brand': 'Canon',
     'img': './img/cameras/EOS 7D Mark II.jpg',
     'age': 22},
    {'name': 'EOS 6D',
     'brand': 'Canon',
     'img': './img/cameras/EOS 6D.jpg',
     'age': 22},
    {'name': 'D7000',
     'brand': 'Nikon',
     'img': './img/cameras/D7000.png',
     'age': 22},
    {'name': 'DF',
     'brand': 'Nikon',
     'img': './img/cameras/DFpng.png',
     'age': 22},
     {'name': 'D810',
     'brand': 'Nikon',
     'img': './img/cameras/D810.png',
     'age': 22},
     {'name': 'D3X',
     'brand': 'Nikon',
     'img': './img/cameras/D3X.png',
     'age': 22},
     {'name': 'D4S',
     'brand': 'Nikon',
     'img': './img/cameras/D4S.png',
     'age': 22},
     {'name': 'D3200',
     'brand': 'Nikon',
     'img': './img/cameras/D3200.png',
     'age': 22},
     {'name': 'D5300',
     'brand': 'Nikon',
     'img': './img/cameras/D5300.png',
     'age': 22},
  ];

  $scope.orderProp = 'brand';
});